name: chrip_aid
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Navigator
  go_router: ^9.0.3

  # Json Annotation
  json_annotation: ^4.8.0

  # REST Api
  dio: ^5.2.1+1
  retrofit: ^4.0.1
  logger: ^1.4.0

  # Secure Storage
  flutter_secure_storage: ^8.0.0

  # Local Storage
  universal_html: ^2.2.3

  # dotenv
  flutter_dotenv: ^5.1.0

  # DI
  flutter_riverpod: ^2.3.6

  # Internationalization
  intl: ^0.18.1

  # Calender
  table_calendar: ^3.0.9

  # Validator
  validators: ^3.0.0

  # FCM
  firebase_messaging: ^14.6.5
  firebase_core: ^2.15.0
  flutter_local_notifications: ^15.1.0+1

  # Google Map
  google_maps_flutter: ^2.2.1
  flutter_google_places: ^0.3.0
  google_maps_flutter_android: ^2.5.1
  google_maps_flutter_platform_interface: ^2.4.1
  google_maps_webservice: ^0.0.19
  google_api_headers:
  google_geocoding: ^0.2.0

  # Percent indicator 추가
  percent_indicator: ^4.2.3
  step_progress_indicator: ^1.0.2
  sleek_circular_slider: ^2.0.1
  progress_indicators: ^1.0.0
  liquid_progress_indicator: ^0.4.0

  # Sliding Up Panel
  flutter_sliding_up_panel: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  # REST Api
  build_runner: ^2.4.6
  retrofit_generator: ^6.0.0+3
  json_serializable: ^6.6.1

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/pajukids_house.jpg
    - assets/image/choco_pie.jpg
    - .env